version: '{build}'
init:
- cmd: >-
    npm update -g
    
    npm install -g cordova

install:
- ps: >-
    $secureString = convertto-securestring "GrEC`$2015" -asplaintext -force
    
    $secureString2 = convertto-securestring "GrECo2017" -asplaintext -force
    
    Import-PfxCertificate -FilePath C:\projects\windowsapp\certification\certificate\GrECo.pfx -CertStoreLocation Cert:\CurrentUser\My -Password $secureString
    
    Import-PfxCertificate -FilePath C:\projects\windowsapp\certification\certificate\GrECo-winstore.pfx -CertStoreLocation Cert:\CurrentUser\My -Password $secureString2

build_script:
- cmd: >-
    cd src
    
    cordova platform add windows
    
    cordova platform ls
    
    cordova build --release windows --appx=uap --archs=arm
    
before_deploy:

- cmd: 7z a AppPackages.zip C:\projects\windowsapp\src\platforms\windows\AppPackages\

deploy:
- provider: GitHub
  auth_token:
    secure: xAXPZfdZhu/tHAQUazH+7X66AElkJymfj9U4Kb7itHOomRl+15F2HMJWMyzeRLof
  artifact: C:\projects\windowsapp\src\AppPackages.zip